baseURL = "https://diavohra.com/"
languageCode = "en-us"
title = "Dia Vohra"
theme = "hugograyscale"
publishDir = "docs"
googleAnalytics = "G-J5FX4QPX1X"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Personal website of Dia Vohra"

[Author]
    name = "Dia Vohra"
    email = "diavohra212@gmail.com"

[Social]
    twitter = "stream_running"
