baseURL = "https://diavohra.com/"
languageCode = "en-us"
title = "Dia Vohra"
theme = "hugograyscale"
publishDir = "docs"
googleAnalytics = "G-J5FX4QPX1X"
disableKinds = ["taxonomy"]

[params]
    # Provide some metadata for search and indexing services
    author = "Dia Vohra"
    email = "diavohra212@gmail.com"
    description = "Personal website of Dia Vohra"

[Social]
    twitter = "stream_running"
